# Generated by Django 5.2.5 on 2025-12-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.CharField(default='person', max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('star_rating', models.IntegerField(default=5)),
                ('bath_count', models.IntegerField(default=0)),
                ('bed_count', models.IntegerField(default=0)),
                ('amenity', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
