# Generated by Django 5.2.5 on 2025-12-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('created_at', models.DateField()),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
